import { PLATFORM_FREE_REVIEWS } from "../../../package/lib/apiKey.service.js";

const SEVERITY_ORDER: Record<string, number> = { high: 0, medium: 1, low: 2 };
const SEVERITY_LABEL: Record<string, string> = {
  high: "Should fix",
  medium: "Worth fixing",
  low: "Nit",
};

const SEVERITY_EMOJI: Record<string, string> = {
  high: "🔴",
  medium: "🟡",
  low: "🟢",
};

const FRONTEND_BASE_URL = process.env.FRONTEND_BASE_URL || "https://custom-ai-code-reviewer.vercel.app";

export type CommentIssue = {
  id: string;
  file: string;
  line: number;
  severity: string;
  problem: string;
  fix?: string | null;
};

function buildApplyLink(
  owner: string,
  repo: string,
  prNumber: number,
  issueId: string,
): string {
  return `${FRONTEND_BASE_URL}/repo/${owner}/${repo}/pr/${prNumber}?issue=${issueId}`;
}

function formatReasonForReview(usedCodebaseContext: boolean): string {
  const contextNote = usedCodebaseContext
    ? " I also pulled in related code from elsewhere in the repo for context, "
    : " ";

  return `I went through the diff against this repo's review rules,${contextNote}and had Claude score it. The score starts at **100** and drops a bit per issue depending on severity — 🔴 high, 🟡 medium, 🟢 low. Treat it as a rough signal, not a verdict.`;
}

export function formatReviewComment(
  parsed: { summary?: string; score?: number },
  issues: CommentIssue[],
  gifURL: string | null | undefined,
  linkContext: { owner: string; repo: string; prNumber: number },
  usedCodebaseContext: boolean,
): string {
  const score = parsed.score ?? "N/A";
  const summary = parsed.summary?.trim() || "Review complete.";

  const counts = {
    high: issues.filter((i) => i.severity === "high").length,
    medium: issues.filter((i) => i.severity === "medium").length,
    low: issues.filter((i) => i.severity === "low").length,
  };

  const sections: string[] = [];

  sections.push("## 🤖 CodeRefyn Review");

  // Clicking the summary reveals *why* this review happened, not the finding
  // itself — the finding is the always-visible headline.
  sections.push(
    [
      "<details>",
      `<summary>${summary}</summary>`,
      "",
      formatReasonForReview(usedCodebaseContext),
      "",
      "</details>",
    ].join("\n"),
  );

  if (gifURL) {
    sections.push(`![review-reaction](${gifURL})`);
  }

  sections.push(
    issues.length > 0
      ? `**Score:** ${score}/100  ·  **Issues:** ${issues.length}  (🔴 ${counts.high} high · 🟡 ${counts.medium} medium · 🟢 ${counts.low} low)`
      : `**Score:** ${score}/100`,
  );

  if (issues.length === 0) {
    sections.push("✅ Nothing blocking from me here — this looks good to merge.");
    sections.push(["---", "*Generated by CodeRefyn*"].join("\n"));
    return sections.join("\n\n") + "\n";
  }

  if (counts.high === 0) {
    sections.push("✅ Nothing here should block the merge — just a few things worth a look below.");
  }

  sections.push("---");
  sections.push(`### 🔍 Issues (${issues.length})`);

  const sorted = [...issues].sort(
    (a, b) => (SEVERITY_ORDER[a.severity] ?? 3) - (SEVERITY_ORDER[b.severity] ?? 3),
  );

  const issueBlocks = sorted.map((issue, index) => {
    const label = SEVERITY_LABEL[issue.severity] ?? "Note";
    const emoji = SEVERITY_EMOJI[issue.severity] ?? "⚪";
    const location = issue.line ? `${issue.file}:${issue.line}` : issue.file;
    const preview =
      issue.problem.length > 80 ? `${issue.problem.slice(0, 77)}...` : issue.problem;

    const body = [
      "<details>",
      `<summary>${emoji} <b>${index + 1}.</b> \`${location}\` — ${preview}</summary>`,
      "",
      `**${label}:** ${issue.problem}`,
    ];

    if (issue.fix) {
      body.push("", `**Suggested fix:** ${issue.fix}`);

      if (issue.id) {
        body.push(
          "",
          `[Apply Suggestion →](${buildApplyLink(linkContext.owner, linkContext.repo, linkContext.prNumber, issue.id)})`,
        );
      }
    }

    body.push("", "</details>");
    return body.join("\n");
  });

  sections.push(issueBlocks.join("\n\n"));
  sections.push(["---", "*Generated by CodeRefyn*"].join("\n"));

  return sections.join("\n\n") + "\n";
}

export function formatQuotaExceededComment(): string {
  return `## Code Review Unavailable

You've used all **${PLATFORM_FREE_REVIEWS} free platform reviews**. To continue receiving AI code reviews, add your own Claude API key in the [CodeRefyn dashboard](${FRONTEND_BASE_URL}/ai-usage).

Once configured, all reviews will use your key and token usage will appear on the AI Usage page.`;
}
