import {
  getOctokit,
  getDifferenceData,
  getReviewRules,
} from "./github.service.js";
import {
  getAIReview,
  reviewPrompt,
  parseAIResponse,
  getRevieType,
  getCodeDiff,
  generateRelevantSearchQuery,
  createTokenAccumulator,
} from "./ai.service.js";
import { db } from "../../../package/db/prisma.js";
import {
  vectorDBExists,
  waitForVectorIndex,
  retrieveContextForDiff,
  toIndexName,
} from "./rag.service.js";
import { findGIF } from "./gif.service.js";
import { getGifName } from "../../../package/ai/gif.js";
import {
  resolveReviewApiKey,
  incrementPlatformReviewCount,
  recordTokenUsage,
  PLATFORM_FREE_REVIEWS,
} from "../../../package/lib/apiKey.service.js";

export type PRReviewJobData = {
  installationId: number;
  owner: string;
  repo: string;
  prNumber: number;
  prTitle?: string;
  prAuthor?: string;
  userId?: string;
};

export function formatReviewComment(parsed: any, gifURL?: string | null): string {
  const score = parsed.score ?? "N/A";
  const issues: any[] = parsed.issues ?? [];

  const grouped = {
    high: issues.filter((i) => i.severity === "high"),
    medium: issues.filter((i) => i.severity === "medium"),
    low: issues.filter((i) => i.severity === "low"),
  };

  let md = `## Code Review\n\n`;

  if (gifURL) {
    md += `![review-gif](${gifURL})\n\n`;
  }

  md += `${parsed.summary}\n\n`;

  md += `Score: ${score}/100`;
  if (issues.length > 0) {
    md += ` (${grouped.high.length} high, ${grouped.medium.length} medium, ${grouped.low.length} low)`;
  }
  md += `\n\n`;

  if (issues.length === 0) {
    md += `No issues found. This looks good to me.\n`;
    return md;
  }

  md += `---\n\n`;

  function renderSection(title: string, arr: any[]) {
    if (arr.length === 0) return "";

    return `
### ${title}

${arr
  .map(
    (issue) => `
- ${issue.file}:${issue.line}
  - Category: ${issue.category}
  - Issue: ${issue.problem}
  - Suggestion: ${issue.fix}
`,
  )
  .join("\n")}
`;
  }

  md += renderSection("High severity issues", grouped.high);
  md += renderSection("Medium severity issues", grouped.medium);
  md += renderSection("Low severity issues", grouped.low);

  md += `\n---\n`;
  md += `Generated by CodeRefyn\n`;

  return md;
}

function formatQuotaExceededComment(): string {
  return `## Code Review Unavailable

You've used all **${PLATFORM_FREE_REVIEWS} free platform reviews**. To continue receiving AI code reviews, add your own Claude API key in the [CodeRefyn dashboard](https://custom-ai-code-reviewer.vercel.app/ai-usage).

Once configured, all reviews will use your key and token usage will appear on the AI Usage page.`;
}

async function getReviewGifUrl(
  summary: string | null | undefined,
  apiKey: string,
  usage: ReturnType<typeof createTokenAccumulator>,
): Promise<string | null> {
  try {
    const gifQuery = await getGifName(summary, apiKey, usage);
    return await findGIF(gifQuery);
  } catch (error) {
    console.error("Skipping review GIF", error);
    return null;
  }
}

async function resolveUserId(
  owner: string,
  repo: string,
  userId?: string,
): Promise<string | null> {
  if (userId) return userId;

  const repository = await db.repository.findUnique({
    where: { owner_name: { owner, name: repo } },
    select: { userId: true },
  });
  return repository?.userId ?? null;
}

export async function runPRReview(data: PRReviewJobData) {
  const { installationId, owner, repo, prNumber, prTitle, prAuthor } = data;

  const octokit = await getOctokit(installationId);
  const userId = await resolveUserId(owner, repo, data.userId);

  if (!userId) {
    console.log(`No user found for ${owner}/${repo} — skipping review`);
    return;
  }

  const resolvedKey = await resolveReviewApiKey(userId);
  if (!resolvedKey) {
    console.log(`User ${userId} has no API key and free reviews exhausted`);
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: formatQuotaExceededComment(),
    });
    return;
  }

  const { apiKey, source } = resolvedKey;
  const tokenUsage = createTokenAccumulator();

  const difference = await getDifferenceData(octokit, owner, repo, prNumber);
  await octokit.rest.repos.listCollaborators({
    owner,
    repo,
  });
  const rules = await getReviewRules(octokit, owner, repo, prNumber);
  const reviewType = (await getRevieType(difference, apiKey, tokenUsage)) as any;
  const indexName = toIndexName(owner, repo);
  let relevantCode: Awaited<ReturnType<typeof retrieveContextForDiff>> | undefined;
  const processedDiff = (await getCodeDiff(difference)) as any;

  if (reviewType === "feature") {
    const indexReady =
      (await vectorDBExists(indexName)) ||
      (await waitForVectorIndex(indexName));

    if (indexReady) {
      const searchQuery = await generateRelevantSearchQuery(
        processedDiff,
        apiKey,
        tokenUsage,
      );
      relevantCode = await retrieveContextForDiff({
        diff: difference,
        semanticQuery: searchQuery,
        indexName,
        topK: 8,
      });
      console.log(
        `RAG context for ${owner}/${repo}#${prNumber}: ${relevantCode.length} AST chunks`,
      );
    } else {
      console.log(
        `Vector index "${indexName}" not ready — reviewing without RAG context`,
      );
    }
  }

  const prompt = reviewPrompt(difference, rules, relevantCode);
  const aiResponse = await getAIReview(prompt, apiKey, tokenUsage);
  const cleanText = aiResponse
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim();
  const parsedPrompt = parseAIResponse(cleanText);

  if (!parsedPrompt) {
    console.log("Failed to parse AI response");
    return;
  }
  const gifUrl = await getReviewGifUrl(parsedPrompt.summary, apiKey, tokenUsage);

  const commentBody = formatReviewComment(parsedPrompt, gifUrl);
  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body: commentBody,
  });

  const repository = await db.repository.findUnique({
    where: { owner_name: { owner, name: repo } },
  });

  if (!repository) {
    console.log(
      `repo ${owner}/${repo} not found in DB after upsert — skipping save`,
    );
    return aiResponse;
  }

  const savedReview = await db.pRReview.create({
    data: {
      prNumber,
      prTitle: prTitle ?? null,
      summary: parsedPrompt.summary ?? null,
      score: parsedPrompt.score ?? 0,
      repositoryId: repository.id,
      author: owner,
      prAuthor: prAuthor,
      commitSHA: "",
    },
  });

  if (parsedPrompt.issues?.length > 0) {
    await db.issue.createMany({
      data: parsedPrompt.issues.map((issue: any) => ({
        reviewId: savedReview.id,
        file: issue.file,
        line: issue.line,
        category: issue.category,
        severity: issue.severity,
        problem: issue.problem,
        fix: issue.fix,
      })),
    });
  }

  await recordTokenUsage({
    userId,
    reviewId: savedReview.id,
    inputTokens: tokenUsage.inputTokens,
    outputTokens: tokenUsage.outputTokens,
    source,
  });

  if (source === "platform") {
    await incrementPlatformReviewCount(userId);
  }

  console.log(
    `review saved to DB for ${owner}/${repo}#${prNumber} (${tokenUsage.inputTokens + tokenUsage.outputTokens} tokens, ${source})`,
  );
  return aiResponse;
}
