import {
  getOctokit,
  getDifferenceData,
  getReviewRules,
} from "./github.service.js";
import {
  getAIReview,
  reviewPrompt,
  parseAIResponse,
  getRevieType,
  getCodeDiff,
  generateRelevantSearchQuery,
  createTokenAccumulator,
} from "./ai.service.js";
import { db } from "../../../package/db/prisma.js";
import {
  vectorDBExists,
  waitForVectorIndex,
  retrieveContextForDiff,
  toIndexName,
} from "./rag.service.js";
import { findGIF } from "./gif.service.js";
import { getGifName } from "../../../package/ai/gif.js";
import {
  resolveReviewApiKey,
  incrementPlatformReviewCount,
  recordTokenUsage,
  PLATFORM_FREE_REVIEWS,
} from "../../../package/lib/apiKey.service.js";

export type PRReviewJobData = {
  installationId: number;
  owner: string;
  repo: string;
  prNumber: number;
  prTitle?: string;
  prAuthor?: string;
  userId?: string;
};

const SEVERITY_ORDER: Record<string, number> = { high: 0, medium: 1, low: 2 };
const SEVERITY_LABEL: Record<string, string> = {
  high: "Should fix",
  medium: "Worth fixing",
  low: "nit",
};

export function formatReviewComment(parsed: any, gifURL?: string | null): string {
  const score = parsed.score ?? "N/A";
  const issues: any[] = parsed.issues ?? [];

  const counts = {
    high: issues.filter((i) => i.severity === "high").length,
    medium: issues.filter((i) => i.severity === "medium").length,
    low: issues.filter((i) => i.severity === "low").length,
  };

  let md = `## Code Review\n\n`;

  if (gifURL) {
    md += `![review-gif](${gifURL})\n\n`;
  }

  if (parsed.summary) {
    md += `${parsed.summary}\n\n`;
  }

  md += `**Score: ${score}/100**`;
  if (issues.length > 0) {
    md += ` · ${counts.high} high, ${counts.medium} medium, ${counts.low} low`;
  }
  md += `\n\n`;

  if (issues.length === 0) {
    md += `Nothing blocking from me here — this looks good to merge.\n\n`;
    md += `---\nGenerated by CodeRefyn\n`;
    return md;
  }

  md += `---\n\n`;

  const sorted = [...issues].sort(
    (a, b) =>
      (SEVERITY_ORDER[a.severity] ?? 3) - (SEVERITY_ORDER[b.severity] ?? 3),
  );

  md += sorted
    .map((issue) => {
      const label = SEVERITY_LABEL[issue.severity] ?? "Note";
      const location = issue.line
        ? `\`${issue.file}:${issue.line}\``
        : `\`${issue.file}\``;
      const suggestion = issue.fix ? ` _Suggestion: ${issue.fix}_` : "";
      return `- ${location} — **${label}:** ${issue.problem}${suggestion}`;
    })
    .join("\n");

  md += `\n\n---\nGenerated by CodeRefyn\n`;

  return md;
}

function formatQuotaExceededComment(): string {
  return `## Code Review Unavailable

You've used all **${PLATFORM_FREE_REVIEWS} free platform reviews**. To continue receiving AI code reviews, add your own Claude API key in the [CodeRefyn dashboard](https://custom-ai-code-reviewer.vercel.app/ai-usage).

Once configured, all reviews will use your key and token usage will appear on the AI Usage page.`;
}

async function getReviewGifUrl(
  parsed: any,
  apiKey: string,
  usage: ReturnType<typeof createTokenAccumulator>,
): Promise<string | null> {
  try {
    const issues: any[] = parsed?.issues ?? [];
    const gifQuery = await getGifName(parsed?.summary, apiKey, usage, {
      score: parsed?.score ?? null,
      totalIssues: issues.length,
      highSeverityCount: issues.filter((i) => i.severity === "high").length,
    });
    return await findGIF(gifQuery);
  } catch (error) {
    console.error("Skipping review GIF", error);
    return null;
  }
}

async function resolveUserId(
  owner: string,
  repo: string,
  userId?: string,
): Promise<string | null> {
  if (userId) return userId;

  const repository = await db.repository.findUnique({
    where: { owner_name: { owner, name: repo } },
    select: { userId: true },
  });
  return repository?.userId ?? null;
}

export async function runPRReview(data: PRReviewJobData) {
  const { installationId, owner, repo, prNumber, prTitle, prAuthor } = data;

  const octokit = await getOctokit(installationId);
  const userId = await resolveUserId(owner, repo, data.userId);

  if (!userId) {
    console.log(`No user found for ${owner}/${repo} — skipping review`);
    return;
  }

  const resolvedKey = await resolveReviewApiKey(userId);
  if (!resolvedKey) {
    console.log(`User ${userId} has no API key and free reviews exhausted`);
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: formatQuotaExceededComment(),
    });
    return;
  }

  const { apiKey, source } = resolvedKey;
  const tokenUsage = createTokenAccumulator();

  const difference = await getDifferenceData(octokit, owner, repo, prNumber);
  await octokit.rest.repos.listCollaborators({
    owner,
    repo,
  });
  const rules = await getReviewRules(octokit, owner, repo, prNumber);
  const reviewType = (await getRevieType(difference, apiKey, tokenUsage)) as any;
  const indexName = toIndexName(owner, repo);
  let relevantCode: Awaited<ReturnType<typeof retrieveContextForDiff>> | undefined;
  const processedDiff = (await getCodeDiff(difference)) as any;

  if (reviewType === "feature") {
    const indexReady =
      (await vectorDBExists(indexName)) ||
      (await waitForVectorIndex(indexName));

    if (indexReady) {
      const searchQuery = await generateRelevantSearchQuery(
        processedDiff,
        apiKey,
        tokenUsage,
      );
      relevantCode = await retrieveContextForDiff({
        diff: difference,
        semanticQuery: searchQuery,
        indexName,
        topK: 8,
      });
      console.log(
        `RAG context for ${owner}/${repo}#${prNumber}: ${relevantCode.length} AST chunks`,
      );
    } else {
      console.log(
        `Vector index "${indexName}" not ready — reviewing without RAG context`,
      );
    }
  }

  const prompt = reviewPrompt(difference, rules, relevantCode);
  const aiResponse = await getAIReview(prompt, apiKey, tokenUsage);
  const cleanText = aiResponse
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim();
  const parsedPrompt = parseAIResponse(cleanText);

  if (!parsedPrompt) {
    console.log("Failed to parse AI response");
    return;
  }
  const gifUrl = await getReviewGifUrl(parsedPrompt, apiKey, tokenUsage);

  const commentBody = formatReviewComment(parsedPrompt, gifUrl);
  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body: commentBody,
  });

  const repository = await db.repository.findUnique({
    where: { owner_name: { owner, name: repo } },
  });

  if (!repository) {
    console.log(
      `repo ${owner}/${repo} not found in DB after upsert — skipping save`,
    );
    return aiResponse;
  }

  const savedReview = await db.pRReview.create({
    data: {
      prNumber,
      prTitle: prTitle ?? null,
      summary: parsedPrompt.summary ?? null,
      score: parsedPrompt.score ?? 0,
      repositoryId: repository.id,
      author: owner,
      prAuthor: prAuthor,
      commitSHA: "",
    },
  });

  if (parsedPrompt.issues?.length > 0) {
    await db.issue.createMany({
      data: parsedPrompt.issues.map((issue: any) => ({
        reviewId: savedReview.id,
        file: issue.file,
        line: issue.line,
        category: issue.category,
        severity: issue.severity,
        problem: issue.problem,
        fix: issue.fix,
      })),
    });
  }

  await recordTokenUsage({
    userId,
    reviewId: savedReview.id,
    inputTokens: tokenUsage.inputTokens,
    outputTokens: tokenUsage.outputTokens,
    source,
  });

  if (source === "platform") {
    await incrementPlatformReviewCount(userId);
  }

  console.log(
    `review saved to DB for ${owner}/${repo}#${prNumber} (${tokenUsage.inputTokens + tokenUsage.outputTokens} tokens, ${source})`,
  );
  return aiResponse;
}
