import {
  getOctokit,
  getDifferenceData,
  getReviewRules,
} from "./github.service.js";
import { getAIReview, reviewPrompt, parseAIResponse, getRevieType, getCodeDiff, generateRelevantSearchQuery } from "./ai.service.js";
import { db } from "../../../package/db/prisma.js";
import {vectorDBExists, createEmbeddings, saveToVectorDB, searchRelevantEmbeddings, toIndexName} from "./rag.service.js"
import { diff } from "node:util";

export function formatReviewComment(parsed: any): string {
  const score = parsed.score ?? "N/A";
  const issues: any[] = parsed.issues ?? [];

  const grouped = {
    high: issues.filter((i) => i.severity === "high"),
    medium: issues.filter((i) => i.severity === "medium"),
    low: issues.filter((i) => i.severity === "low"),
  };

  let md = `## Code Review\n\n`;

  md += `${parsed.summary}\n\n`;

  md += `Score: ${score}/100`;
  if (issues.length > 0) {
    md += ` (${grouped.high.length} high, ${grouped.medium.length} medium, ${grouped.low.length} low)`;
  }
  md += `\n\n`;

  if (issues.length === 0) {
    md += `No issues found. This looks good to me.\n`;
    return md;
  }

  md += `---\n\n`;

  function renderSection(title: string, arr: any[]) {
    if (arr.length === 0) return "";

    return `
### ${title}

${arr
  .map(
    (issue) => `
- ${issue.file}:${issue.line}
  - Category: ${issue.category}
  - Issue: ${issue.problem}
  - Suggestion: ${issue.fix}
`
  )
  .join("\n")}
`;
  }

  md += renderSection("High severity issues", grouped.high);
  md += renderSection("Medium severity issues", grouped.medium);
  md += renderSection("Low severity issues", grouped.low);

  md += `\n---\n`;
  md += `Generated by ReviewPilot\n`;

  return md;
}
export type PRReviewJobData = {
  installationId: number;
  owner: string;
  repo: string;
  prNumber: number;
  prTitle?: string;
};

export async function runPRReview(data: PRReviewJobData) {
  const { installationId, owner, repo, prNumber, prTitle } = data;
  let dbName = ""

  const createVectorDB = await vectorDBExists(dbName) as boolean

  if(createVectorDB){
    let values = {}
    
    const embeddings = await createEmbeddings(values) as any
    const finalSaved = await saveToVectorDB(embeddings)
    console.log(finalSaved)
  }

  const octokit = await getOctokit(installationId);
  const difference = await getDifferenceData(octokit, owner, repo, prNumber);
  const { data: collaborators } = await octokit.rest.repos.listCollaborators({
    owner,
    repo,
  });
  const rules = await getReviewRules(octokit, owner, repo, prNumber);
  const reviewType = await getRevieType(difference) as any
  const indexName = toIndexName(owner, repo)
  const DBExsists = await vectorDBExists(indexName)
  let relevantCode:any
  console.log("<============= reviewType ===============> \n", reviewType)
  if(reviewType === "feature" && DBExsists) {
    const processedDiff = await getCodeDiff(difference) as any
    const searchQuery = await generateRelevantSearchQuery(processedDiff)
    console.log("<=================== searchQuery ===================> \n", searchQuery)
    const query = {
      text: searchQuery,
      indexName: indexName,
      topK: 5,
    }
    relevantCode = await searchRelevantEmbeddings(query)
  }

  const prompt = reviewPrompt(difference, rules, relevantCode);
  const aiResponse = await getAIReview(prompt);
  const cleanText = aiResponse
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim();
  const parsedPrompt = parseAIResponse(cleanText);

  if (!parsedPrompt) {
    console.log("❌ Failed to parse AI response");
    return;
  }

  const commentBody = formatReviewComment(parsedPrompt);
  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body: commentBody,
  });

  const repository = await db.repository.findUnique({
    where: { owner_name: { owner, name: repo } },
  });

  if (!repository) {
    console.log(
      `repo ${owner}/${repo} not found in DB after upsert — skipping save`,
    );
    return aiResponse;
  }

  const savedReview = await db.pRReview.create({
    data: {
      prNumber,
      prTitle: prTitle ?? null,
      summary: parsedPrompt.summary ?? null,
      score: parsedPrompt.score ?? 0,
      repositoryId: repository.id,
      author: owner,
      commitSHA: "",
    },
  });

  if (parsedPrompt.issues?.length > 0) {
    await db.issue.createMany({
      data: parsedPrompt.issues.map((issue: any) => ({
        reviewId: savedReview.id,
        file: issue.file,
        line: issue.line,
        category: issue.category,
        severity: issue.severity,
        problem: issue.problem,
        fix: issue.fix,
      })),
    });
  }

  console.log(`review saved to DB for ${owner}/${repo}#${prNumber}`);
  return aiResponse;
}
