import { PLATFORM_FREE_REVIEWS } from "../../../package/lib/apiKey.service.js";

const SEVERITY_ORDER: Record<string, number> = { high: 0, medium: 1, low: 2 };
const SEVERITY_LABEL: Record<string, string> = {
  high: "Should fix",
  medium: "Worth fixing",
  low: "nit",
};

const SEVERITY_EMOJI: Record<string, string> = {
  high: "🔴",
  medium: "🟡",
  low: "🟡",
};

const FRONTEND_BASE_URL = process.env.FRONTEND_BASE_URL || "https://custom-ai-code-reviewer.vercel.app";

export type CommentIssue = {
  id: string;
  file: string;
  line: number;
  severity: string;
  problem: string;
  fix?: string | null;
};

function buildApplyLink(
  owner: string,
  repo: string,
  prNumber: number,
  issueId: string,
): string {
  return `${FRONTEND_BASE_URL}/repo/${owner}/${repo}/pr/${prNumber}?issue=${issueId}`;
}

function formatWhyAndHow(usedCodebaseContext: boolean): string {
  const contextNote = usedCodebaseContext
    ? " I also pulled in a bit of related code from elsewhere in the repo for context, "
    : " ";

  return [
    "<details>",
    "<summary>› Why and how this review</summary>",
    "",
    `I went through the diff against this repo's review rules,${contextNote}and had Claude score it. The score starts at 100 and drops a bit per issue depending on severity — high, medium, or low. Treat it as a rough signal, not a verdict.`,
    "",
    "</details>",
    "",
  ].join("\n");
}

export function formatReviewComment(
  parsed: { summary?: string; score?: number },
  issues: CommentIssue[],
  gifURL: string | null | undefined,
  linkContext: { owner: string; repo: string; prNumber: number },
  usedCodebaseContext: boolean,
): string {
  const score = parsed.score ?? "N/A";

  const counts = {
    high: issues.filter((i) => i.severity === "high").length,
    medium: issues.filter((i) => i.severity === "medium").length,
    low: issues.filter((i) => i.severity === "low").length,
  };

  let md = `## Code Review\n\n`;
  md += formatWhyAndHow(usedCodebaseContext);
  md += "\n";

  if (gifURL) {
    md += `![review-gif](${gifURL})\n\n`;
  }

  if (parsed.summary) {
    md += `${parsed.summary}\n\n`;
  }

  md += `**Score: ${score}/100**`;
  if (issues.length > 0) {
    md += ` · ${counts.high} high, ${counts.medium} medium, ${counts.low} low`;
  }
  md += `\n\n`;

  if (issues.length === 0) {
    md += `✓ Nothing blocking from me here — this looks good to merge.\n\n`;
    md += `---\nGenerated by CodeRefyn\n`;
    return md;
  }

  if (counts.high === 0) {
    md += `✓ Nothing here should block the merge — just a few things worth a look below.\n\n`;
  }

  md += `---\n\n`;

  const sorted = [...issues].sort(
    (a, b) =>
      (SEVERITY_ORDER[a.severity] ?? 3) - (SEVERITY_ORDER[b.severity] ?? 3),
  );

  md += sorted
    .map((issue) => {
      const label = SEVERITY_LABEL[issue.severity] ?? "Note";
      const emoji = SEVERITY_EMOJI[issue.severity] ?? "⚪";
      const location = issue.line ? `${issue.file}:${issue.line}` : issue.file;
      const preview =
        issue.problem.length > 80
          ? `${issue.problem.slice(0, 77)}...`
          : issue.problem;

      const body = [
        `<details>`,
        `<summary>${emoji} \`${location}\` — ${preview}</summary>`,
        "",
        `**${label}:** ${issue.problem}`,
        "",
      ];

      if (issue.fix) {
        body.push(`_Suggested fix:_ ${issue.fix}`, "");

        if (issue.id) {
          body.push(
            `[Apply Suggestion →](${buildApplyLink(linkContext.owner, linkContext.repo, linkContext.prNumber, issue.id)})`,
            "",
          );
        }
      }

      body.push(`</details>`, "");
      return body.join("\n");
    })
    .join("\n");

  md += `\n---\nGenerated by CodeRefyn\n`;

  return md;
}

export function formatQuotaExceededComment(): string {
  return `## Code Review Unavailable

You've used all **${PLATFORM_FREE_REVIEWS} free platform reviews**. To continue receiving AI code reviews, add your own Claude API key in the [CodeRefyn dashboard](${FRONTEND_BASE_URL}/ai-usage).

Once configured, all reviews will use your key and token usage will appear on the AI Usage page.`;
}
